version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: arkham_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1tt2svES!
      - POSTGRES_DB=arkham_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
